// The hand-drawn accents of a video: hdf/accents.resolved.json (what the build asked for, every target a box
// in composition pixels) becomes hdf/accents.js, a film of the handdrawn package drawing those marks on no
// stock, rendered to hdf/accents.webm (VP9 with alpha) that the composition plays full-frame on its top
// layer. Only re-rendered when the film changed. Used by `nv build` and `nv accents`.
import { spawnSync } from 'node:child_process';
import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, '../../../..');
const HDF = join(REPO, 'handdrawn');
const shown = (p) => { const r = relative(process.cwd(), p); return r.startsWith('..') ? p : r; };

export function formatOf(W, H) {
  const r = W / H;
  if (Math.abs(r - 16 / 9) < 0.01) return '16:9';
  if (Math.abs(r - 9 / 16) < 0.01) return '9:16';
  if (Math.abs(r - 1) < 0.01) return '1:1';
  throw new Error(`hand accents need a 16:9, 9:16 or 1:1 composition (this one is ${W}x${H})`);
}

export function filmSource(S, fileDir) {
  const core = relative(fileDir, join(HDF, 'core', 'index.js')).split('\\').join('/');
  const K = 1080 / Math.min(S.W, S.H), D = Math.ceil(S.dur * 12 - 1e-9) / 12, ar = formatOf(S.W, S.H);
  const look = String(S.look ?? 'paperInk');
  const base = look.split('~')[0];
  return `// Generated by nv build from hdf/accents.resolved.json; edit the marks in build.mjs, not here.
// The video's hand-drawn accents, drawn on no stock (rendered with --alpha webm) over the composition.
import { film, shot, paper, meta, ramp, ease, withLook, underline, circleAround, arrowTo, starburst, highlight, strike,
  bracket, tickMark, crossMark, question, callout, textBox, writeOn, writer, loops } from '${core.startsWith('.') ? core : `./${core}`}';

const S = ${JSON.stringify({ ink: S.ink, colors: S.colors, w: S.w ?? null, marks: S.marks })};
const K = ${K};   // composition pixels -> hdf units (1080 on the short side)
export const LOOK = withLook('${base}', { name: 'nv-accents', palette: { ink: S.ink, accents: S.colors } });
const B = (b) => [b[0] * K, b[1] * K, b[2] * K, b[3] * K];
const P = (p) => [p[0] * K, p[1] * K];
const at = (m) => (m.box ? B(m.box) : m.point ? P(m.point) : m.from ? P(m.from) : null);
const role = (c) => (c === undefined ? 'accents.0' : typeof c === 'number' ? \`accents.\${c}\` : c);

// How much of a mark is drawn at t: on over [at, at + dur], taken back over [out, out + 0.3], gone at until.
function progress(m, t) {
  if (t < m.at || (m.until !== undefined && t >= m.until)) return 0;
  if (m.out !== undefined && t >= m.out) return 1 - ramp(m.out, m.out + (m.outDur ?? 0.3), t, ease.in);
  return ramp(m.at, m.at + m.dur, t, ease.out);
}

const DRAW = {
  underline: (m, p, o) => underline(at(m), p, { ...o, wavy: m.wavy, double: m.double }),
  circle: (m, p, o) => circleAround(at(m), p, { ...o, turns: m.turns }),
  arrow: (m, p, o) => arrowTo(at(m), m.toBox ? B(m.toBox) : m.to.length === 4 ? B(m.to) : P(m.to), { ...o, p, curve: m.curve ?? 0.25, head: m.head }),
  star: (m, p, o) => starburst(at(m), p, { ...o, n: m.n }),
  highlight: (m, p, o) => highlight(at(m), p, { ...o, role: role(m.color ?? 1), alpha: m.alpha ?? 0.55 }),
  strike: (m, p, o) => strike(at(m), p, { ...o, double: m.double }),
  bracket: (m, p, o) => bracket(at(m), m.side ?? 'left', p, { ...o, kind: m.shape }),
  tick: (m, p, o) => tickMark(at(m), p, o),
  cross: (m, p, o) => crossMark(at(m), p, o),
  question: (m, p, o) => question(at(m), (m.size ?? 80) * K, p, o),
  callout: (m, p, o) => callout(m.text, at(m), { ...o, p, leader: m.leader ?? 'arrow', dir: m.dir, reach: (m.reach ?? 140) * K, size: (m.size ?? 44) * K, curve: m.curve }),
  scribble: (m, p, o) => { const b = at(m); return p > 0 ? loops(b[0] + (b[2] ?? 0) / 2, b[1] + (b[3] ?? 0) / 2, m.dir ?? 0, o.seed, { alpha: p }) : null; },
};

export const accents = shot('accents', ${D}, ({ t, look }) => {
  const ops = [paper(), meta('intent', 'clip')];
  S.marks.forEach((m, i) => {
    const o = { role: role(m.color), seed: 7919 * (i + 1), name: \`m\${i}\`, ...(m.w ?? S.w ? { w: (m.w ?? S.w) * K } : {}) };
    if (m.kind === 'write') {
      if (t < m.at || (m.until !== undefined && t >= m.until)) return;
      const node = textBox(m.text, B(m.box), { size: (m.size ?? 56) * K, align: m.align ?? 'left', role: role(m.color ?? 'ink'), seed: o.seed });
      const sched = { at: m.at, per: 'word', wps: m.wps ?? 2.5 };
      ops.push(writeOn(node, { t, ...sched }));
      if (m.hand) ops.push(writer(node, t, { ...sched, look }));
      return;
    }
    const p = progress(m, t);
    if (p <= 0) return;
    const op = DRAW[m.kind]?.(m, p, o);
    if (op) ops.push(op);
  });
  return ops;
});

export default film({ name: 'accents', look: LOOK, format: '${ar}', timeline: accents });
`;
}

// Resolved spec -> film -> webm, unless nothing changed. Returns { film, webm, rendered, sheet }.
export function buildAccents(projectDir, { force = false, log = (s) => process.stdout.write(s) } = {}) {
  const dir = resolve(projectDir), hdfDir = join(dir, 'hdf');
  const resolved = join(hdfDir, 'accents.resolved.json');
  if (!existsSync(resolved)) throw new Error(`${resolved} is missing: run \`nv build\` (it resolves the marks' targets first)`);
  const S = JSON.parse(readFileSync(resolved, 'utf8'));
  const film = join(hdfDir, 'accents.js'), webm = join(hdfDir, 'accents.webm'), stamp = join(hdfDir, 'accents.hash');
  const src = filmSource(S, hdfDir);
  writeFileSync(film, src);
  const hash = createHash('sha1').update(src).update(String(S.W)).digest('hex');
  if (!force && existsSync(webm) && existsSync(stamp) && readFileSync(stamp, 'utf8').trim() === hash) {
    log(`accents: unchanged (${S.marks.length} marks), ${shown(webm)}\n`);
    return { film, webm, rendered: false };
  }
  const tmp = join(hdfDir, 'render');
  rmSync(tmp, { recursive: true, force: true });
  mkdirSync(tmp, { recursive: true });
  const ar = formatOf(S.W, S.H);
  log(`accents: rendering ${S.marks.length} marks, ${S.dur}s at ${S.W}x${S.H} (hdf, alpha webm)...\n`);
  const r = spawnSync(process.execPath, [join(HDF, 'cli', 'hdf.mjs'), 'render', film, '--alpha', 'webm', '--ar', ar, '--width', String(S.W), '--no-sound', '--out', tmp],
    { cwd: HDF, encoding: 'utf8', maxBuffer: 1 << 26 });
  if (r.status !== 0) throw new Error(`hdf render failed:\n${(r.stderr || r.stdout || '').trim().split('\n').slice(-12).join('\n')}`);
  const outs = readdirSync(tmp).filter((f) => f.endsWith('-alpha.webm')).map((f) => join(tmp, f)).sort((a, b) => statSync(b).mtimeMs - statSync(a).mtimeMs);
  if (!outs.length) throw new Error(`hdf render wrote no alpha webm into ${tmp}:\n${r.stdout}`);
  copyFileSync(outs[0], webm);
  const sheets = readdirSync(tmp).filter((f) => f.endsWith('-sheet.jpg'));
  let sheet;
  if (sheets.length) { mkdirSync(join(dir, '.look'), { recursive: true }); sheet = join(dir, '.look', 'accents-sheet.jpg'); copyFileSync(join(tmp, sheets[0]), sheet); }
  rmSync(tmp, { recursive: true, force: true });
  writeFileSync(stamp, hash + '\n');
  log(`accents: ${shown(webm)}${sheet ? `  (contact sheet ${shown(sheet)})` : ''}\n`);
  return { film, webm, rendered: true, sheet };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    buildAccents(process.argv[2] ?? '.', { force: process.argv.includes('--force') });
  } catch (e) {
    process.stderr.write(`${e.message}\n`);
    process.exit(1);
  }
}
