// Regenerates tests/determinism/goldenFrames.json — the committed golden
// frame hashes checked by tests/determinism/goldenFrames.integration.test.ts
// (v1 plan Session 23, R-16).
//
// Run this ONLY after an intentional pixel-changing change (new behavior,
// bug fix that changes output — see Sessions 6/8 in v1_implementation_plan.md
// for precedent) and say so in the commit message. Running it to silence a
// failing golden test without understanding *why* the pixels changed defeats
// the point of the test.
//
//   bun run scripts/regenerate-goldens.ts
//   git diff tests/determinism/goldenFrames.json   # sanity-check the diff

import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { GOLDEN_EXAMPLES } from "../tests/determinism/support/examples.js";
import {
  GOLDEN_FRACTIONS,
  renderFractionalFrameHashes,
} from "../tests/determinism/support/renderSingleFrame.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const GOLDEN_PATH = resolve(HERE, "../tests/determinism/goldenFrames.json");

async function main(): Promise<void> {
  const examples: Record<string, string[]> = {};
  for (const example of GOLDEN_EXAMPLES) {
    process.stdout.write(`[regenerate-goldens] ${example.name}... `);
    const comp = await example.build();
    const hashes = await renderFractionalFrameHashes(comp, GOLDEN_FRACTIONS);
    examples[example.name] = hashes;
    console.log(hashes.map((h) => h.slice(0, 8)).join(" "));
  }

  const out = {
    $comment:
      "Generated by scripts/regenerate-goldens.ts — do not hand-edit. " +
      "See tests/determinism/goldenFrames.integration.test.ts for what this guards.",
    fractions: GOLDEN_FRACTIONS,
    examples,
  };
  await writeFile(GOLDEN_PATH, `${JSON.stringify(out, null, 2)}\n`, "utf8");
  console.log(`[regenerate-goldens] wrote ${GOLDEN_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
