// Regenerates tests/determinism/goldenFrames.json — the committed golden
// frame hashes checked by tests/determinism/goldenFrames.integration.test.ts
// (v1 plan Session 23, R-16).
//
// Run this ONLY after an intentional pixel-changing change (new behavior,
// bug fix that changes output — see Sessions 6/8 in v1_implementation_plan.md
// for precedent) and say so in the commit message. Running it to silence a
// failing golden test without understanding *why* the pixels changed defeats
// the point of the test.
//
// Goldens are keyed by `${process.platform}-${process.arch}` (skia-canvas
// rasterization differs between its prebuilt per-platform binaries). This
// script only rewrites the CURRENT platform's entry and preserves all
// others — after an intentional pixel change, regenerate on every platform
// that has a committed entry (macOS dev machine + a linux-x64 CI runner).
//
//   bun run scripts/regenerate-goldens.ts
//   git diff tests/determinism/goldenFrames.json   # sanity-check the diff

import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { GOLDEN_EXAMPLES } from "../tests/determinism/support/examples.js";
import {
  GOLDEN_FRACTIONS,
  renderFractionalFrameHashes,
} from "../tests/determinism/support/renderSingleFrame.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const GOLDEN_PATH = resolve(HERE, "../tests/determinism/goldenFrames.json");
const PLATFORM_KEY = `${process.platform}-${process.arch}`;

async function main(): Promise<void> {
  const examples: Record<string, string[]> = {};
  for (const example of GOLDEN_EXAMPLES) {
    process.stdout.write(`[regenerate-goldens] ${example.name}... `);
    const comp = await example.build();
    const hashes = await renderFractionalFrameHashes(comp, GOLDEN_FRACTIONS);
    examples[example.name] = hashes;
    console.log(hashes.map((h) => h.slice(0, 8)).join(" "));
  }

  let existingPlatforms: Record<string, unknown> = {};
  try {
    const prev = JSON.parse(await readFile(GOLDEN_PATH, "utf8")) as {
      platforms?: Record<string, unknown>;
    };
    existingPlatforms = prev.platforms ?? {};
  } catch {
    /* first run — no existing file to preserve */
  }

  const out = {
    $comment:
      "Generated by scripts/regenerate-goldens.ts — do not hand-edit. " +
      "Hashes are keyed by `${process.platform}-${process.arch}` because " +
      "skia-canvas rasterization (antialiasing, font hinting) differs between " +
      "prebuilt binaries per platform; each platform's output is still fully " +
      "deterministic against its own goldens. " +
      "See tests/determinism/goldenFrames.integration.test.ts for what this guards.",
    fractions: GOLDEN_FRACTIONS,
    platforms: {
      ...existingPlatforms,
      [PLATFORM_KEY]: { examples },
    },
  };
  await writeFile(GOLDEN_PATH, `${JSON.stringify(out, null, 2)}\n`, "utf8");
  console.log(
    `[regenerate-goldens] wrote ${GOLDEN_PATH} (platform ${PLATFORM_KEY}, ` +
      `preserved: ${Object.keys(existingPlatforms)
        .filter((k) => k !== PLATFORM_KEY)
        .join(", ") || "none"})`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
