// SOMEONE HELD THIS ONCE. The doodle look: five museum objects nobody uses any more, and a hedgehog who uses
// them anyway, because he is expecting someone. Port of v1 examples/held-once.html, built from the doodle
// recipes (AA to AF) on cutouts regenerated by `hdf photo --v1` from the v1 data URLs.
// Photos: The Metropolitan Museum of Art, Open Access (CC0); credits and sources in held-once-photos.js.
//
// Anchor: the photo in each scene, the prints at the end. Format 1:1, drawn 12 fps. v1 durations moved onto
// the 1/12 s grid; the end holds its sign-off 1.6 s (lint).
// t      dur   scene  paper  object -> becomes           recipe              what changes
// 0.00   3.50  tea    rose   teapot -> a teapot, at last  AC doesItsJob       two cups, the pot tips, only one guest
// 3.50   3.50  wait   mint   watch -> the whole day       AD timeOnIt         a drawn hand goes round, sun sets, he nods off
// 7.00   3.50  sail   sky    violin -> a boat             AA becomesVehicle   sheet-music sail, waves over the hull, a light
// 10.50  4.25  light  lilac  lantern -> a lighthouse      AE nightFalls       it lights, stars, the friend walks in
// 14.75  3.50  two    peach  cup -> a bath for two        AB livesInside      both inside the cup behind the rim, steam
// 18.25  4.50  end    sand   -                            AF printsOnALine    five prints on a line, sign-off
import { film, seq, cel, pen, pentHz, note, burst, LOOKS } from '../core/index.js';
import { hog, doesItsJob, timeOnIt, becomesVehicle, nightFalls, livesInside, printsOnALine, lastFrame } from '../recipes/doodle.js';
import PHOTOS from './held-once-photos.js';

// The hedgehog as a timeless cel (drawn complete): the cast member of every doodle recipe, for sheets and packs.
// dir 1 faces +x; eye 'dot' | 'happy' | 'sleep' | 'wide'; fright lifts the quills.
export const hedgehog = cel('hedgehog', ({ dir = 1, eye = 'happy', scarf = 'accents.0', fright = 0 }) => [
  pen(99, 0, -9, 3, (d) => hog(d, 0, 0, 60, { dir, eye, scarf, fright, w: 4.2 }), { still: true }),
], { box: [-110, -100, 220, 156], inputs: { dir: [-1, 1, 2], fright: [0, 1, 0.25] }, desc: 'the doodle hedgehog with a scarf; eye dot | happy | sleep | wide' });

const tea = doesItsJob({ name: 'tea', photo: PHOTOS.teapot, spout: [0.005, 0.27], handle: [0.86, 0.1] });
const wait = timeOnIt({ name: 'wait', photo: PHOTOS.watch, hub: [0.49, 0.652] });
const sail = becomesVehicle({ name: 'sail', photo: PHOTOS.violin, rot: -Math.PI / 2 });
const light = nightFalls({ name: 'light', photo: PHOTOS.lantern, friend: 'accents.1' });
const two = livesInside({ name: 'two', photo: PHOTOS.cup, x: 540, ground: 905, pivot: [0.37, 1], at: [0.17, 0.56], lip: [0, 0.745], perch: 0.93 });
const SCENES = [tea, wait, sail, light, two];
const end = printsOnALine({ name: 'end', prints: SCENES.map((s) => ({ draw: lastFrame(s), look: s.look })), a: 'someone held this once', b: 'someone still does' });

// ---------- score (v1: a music box, a ticking watch, a bowed line for the sail, two voices) ----------
const score = ({ shots }) => {
  const [t0, t1, t2, t3, t4, t5] = shots.map((s) => s.t0), ev = [];
  const box = (t, o, s, g = 0.2, d = 0.9) => ev.push(note(t, pentHz(o, s, 261.6), d, 'sine', g), note(t, pentHz(o + 1, s, 261.6), d * 0.5, 'triangle', g * 0.25));
  [[0.25, 1, 0], [0.75, 1, 2], [1.25, 1, 4], [1.75, 2, 0], [2.25, 1, 3], [2.75, 1, 4], [3.0, 2, 1]].forEach(([t, o, s]) => box(t0 + t, o, s));
  for (let k = 0; k < 9; k++) ev.push(burst(t1 + 0.25 + k / 3, 0.03, 0.16, k + 1));
  [[1.0, 0, 4], [2.0, 0, 3], [3.0, 0, 1]].forEach(([t, o, s]) => box(t1 + t, o, s, 0.18, 1.4));
  [[0, 0, 0], [0.5, 0, 2], [1.0, 0, 4], [1.5, 1, 0], [2.0, 1, 2], [2.5, 0, 4], [3.0, 1, 0]].forEach(([t, o, s]) => ev.push(note(t2 + t, pentHz(o - 1, s, 261.6), 0.7, 'saw', 0.07)));
  box(t3 + 1.0, 2, 0, 0.3, 2.2); box(t3 + 1.0, 1, 2, 0.2, 2.2);
  [[1.9, 1, 0], [2.4, 1, 2], [3.15, 1, 4], [3.4, 2, 0]].forEach(([t, o, s]) => box(t3 + t, o, s));
  [[0, 1, 0], [0.5, 1, 2], [1.0, 1, 4], [1.5, 2, 0], [2.0, 2, 2], [2.5, 2, 0], [3.0, 1, 4]].forEach(([t, o, s]) => { box(t4 + t, o, s); box(t4 + t + 0.125, o - 1, s, 0.1); });
  [[0, 1, 0], [0.6, 1, 2], [1.2, 1, 4], [2.5, 0, 0], [2.5, 1, 2], [2.5, 2, 0]].forEach(([t, o, s]) => box(t5 + t, o, s, 0.22, 2));
  return { master: 0.5, events: ev };
};

export default film({ name: 'held-once', look: LOOKS.doodlePastel, timeline: seq(...SCENES, end), score, assets: PHOTOS });
